// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Tabler.Docs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250512201844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tabler.Docs.Data.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Tabler.Docs.Model.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tabler.Docs.Data.Country", b =>
                {
                    b.OwnsOne("Medals", "Medals", b1 =>
                        {
                            b1.Property<string>("CountryCode")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Bronze")
                                .HasColumnType("int");

                            b1.Property<int>("Gold")
                                .HasColumnType("int");

                            b1.Property<int>("Silver")
                                .HasColumnType("int");

                            b1.HasKey("CountryCode");

                            b1.ToTable("Countries");

                            b1.WithOwner()
                                .HasForeignKey("CountryCode");
                        });

                    b.Navigation("Medals");
                });
#pragma warning restore 612, 618
        }
    }
}
